POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "esta es una nueva nota 2"
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "nota mate aa asdb",
    "important": true,
    "userId": "624c43d163616da89e3b9987"
}