POST http://localhost:3001/api/users 
Content-Type: application/json

{
    "username": "ppedraza3",
    "name": "Pablo",
    "password": "123"
}

###

POST http://localhost:3001/api/users 
Content-Type: application/json

{
    "username": "casa4",
     "name": "Test User 2",
    "password": "casa"
}
       