version: "3.3"
services:
  mongodb_server:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wayaba
      - MONGO_INITDB_ROOT_PASSWORD=wayaba123
      - MONGO_INITDB_DATABASE=note-db
    volumes:
      - mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
volumes:
  mongodb_server_data: